net stop gztest1
net start gztest1
net stop gztest2
net start gztest2
net stop gztest3
net start gztest3
net stop gztest4
net start gztest4
net stop gztest5
net start gztest5
net stop gztest6
net start gztest6
net stop gztest7
net start gztest7
net stop gztest8
net start gztest8
net stop gztest9
net start gztest9
net stop gztest10
net start gztest10